### ISSUE TITLE
Unknown fields in metric - static labels

### ISSUE THREAD

**Issue by ndelic0** [free/sql_exporter#103]
```
 ./sql_exporter -version
sql_exporter, version 0.5 (branch: master, revision: fc5ed07ee38c5b90bab285392c43edfe32d271c5)
  build user:       root@f24ba5099571
  build date:       20190114-09:24:06
  go version:       go1.11.3

```
collector definition:
```
collector_name: test_data

metrics:
  - metric_name: test_data
    static_labels:
      foo: bar 
    type: counter
    ...
```
when starting sql exporter I'm getting

```
I0928 03:09:09.036610    4796 config.go:18] Loading configuration from sql_exporter.yaml
F0928 03:09:09.038664    4796 main.go:56] Error creating exporter: unknown fields in metric: static_labels
```
Is static_labels field supported?
