### ISSUE TITLE
query="mssql_connections" -> Scan error on column index 0, name "db": unsupported Scan, storing driver.Value type <nil> into type *string`

### ISSUE THREAD

**Issue by iulian-olteanu** [free/sql_exporter#115]
Hello,

We have the following error:

`I0113 15:51:22.498632    9256 promhttp.go:38] Error gathering metrics: [from Gatherer #1] [, collector="mssql_standard", query="mssql_connections"] scanning of query result failed: sql: Scan error on column index 0, name "db": unsupported Scan, storing driver.Value type <nil> into type *string`

The metric definition is   
```
- metric_name: mssql_connections
    type: gauge
    help: 'Number of active connections.'
    key_labels:
      - db
    values: [count]
    query: |
      SELECT DB_NAME(sp.dbid) AS db, COUNT(sp.spid) AS count
      FROM sys.sysprocesses sp
      GROUP BY DB_NAME(sp.dbid)
```

Do you know what is causing it ?
