### ISSUE TITLE
prepare query failed: Error 1064: Unsupported command(COM_STMT_PREPARE) 

### ISSUE THREAD

**Issue by vikingzp** [free/sql_exporter#126]
error report:
prepare query failed: Error 1064: Unsupported command(COM_STMT_PREPARE) 

there is my config yml
```
# Global defaults.
global:
  scrape_timeout_offset: 50000ms
  min_interval: 0s
  max_connections: 3
  max_idle_connections: 3


target:
  data_source_name: 'mysql://rdouser:qI8.pL5(pF@tcp(172.16.224.58:9030)/fbi_sbs_data'
  collectors: 
    - starrocks_collector

collector_files: 
  - "collectors/*.collector.yml"
```

collector.yml
```
# A collector defining standard metrics for Microsoft SQL Server.
#
# It is required that the SQL Server user has the following permissions:
#
#   GRANT VIEW ANY DEFINITION TO
#   GRANT VIEW SERVER STATE TO
#
collector_name: starrocks_collector

# Similar to global.min_interval, but applies to the queries defined by this collector only.
#min_interval: 0s

metrics:
  - metric_name: TEST_metrics
    type: counter
    help: 'TEST_metrics test.'
    key_labels:
      - store
    values: 
      - res
    query: |
        select 123 as res,
        'Peter' as name;
```
