### ISSUE TITLE
Allow metric names to be generated as well as labels

### ISSUE THREAD

**Issue by marksteward** [free/sql_exporter#13]
For certain metrics, it would be nice for column names or values to be included in the metric name instead of the labels. For example, in Oracle, `gv$resource_limit` contains the current value as well as limit for each metric, and the correct way to do this would be to output:

```
oracle_enqueue_locks_limit{instance="1"} 70188
oracle_enqueue_locks_total{instance="1"} 1327
oracle_enqueue_locks_limit{instance="2"} 70188
oracle_enqueue_locks_total{instance="2"} 1174
```

instead of:

```
oracle_resource_limits{instance="1",name="enqueue_locks",stat="limit"} 70188
oracle_resource_limits{instance="1",name="enqueue_locks",stat="total"} 1327
oracle_resource_limits{instance="2",name="enqueue_locks",stat="limit"} 70188
oracle_resource_limits{instance="2",name="enqueue_locks",stat="total"} 1174
```

Currently, to get the first example, I'd need to create a duplicate query for each metric name, which results in a whole load more requests to the DB. Some sort of key_suffixes/value_suffix feature would be great!

**Comment by free** [comment]
You can (and probably should) use [metric relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs) in Prometheus to achieve this.

The way SQL Exporter is currently set up (with fixed metrics registered when the configuration is loaded), this would require serious refactoring for relatively little benefit. Plus, as mentioned above, there is an easy way of achieving this in Prometheus, even if it's slightly inconvenient.

**Comment by marksteward** [comment]
I don't think you can, at least not without similarly knowing the names of all the metrics in advance. Metric relabelling is meant to be for the opposite - taking a metric name and pulling labels out of it.

**Comment by free** [comment]
It is definitely possible. Take a look at https://www.robustperception.io/extracting-labels-from-legacy-metric-names/

Something along these lines should transform your first set of labels into the second (not tested):

```yml
scrape_configs:
  job_name: my_job
  # Usual fields go here to specify targets.
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'oracle_enqueue_locks_(.*)'
    replacement: '${1}'
    target_label: stat
  - source_labels: [__name__]
    regex: 'oracle_enqueue_locks_.*'
    replacement: 'enqueue_locks'
    target_label: name
  - source_labels: [__name__]
    regex: 'oracle_enqueue_locks_.*'
    replacement: 'oracle_resource_limits'
    target_label: __name__
```

**Comment by marksteward** [comment]
I want to go from the second set to the first. They're different metrics, so should have different metric names.

If I can't, it's not game over, but it's a bit awkward for people who aren't familiar with how Oracle lays out its stats tables, as sql_exporter effectively encourages one query = one metric.

**Comment by free** [comment]
Here goes (although I don't think it's necessary for me to write the config just to prove that it's possible):

```yml
scrape_configs:
  job_name: my_job
  metric_relabel_configs:
  # Create a `__tmp_name` label to store new metric name, it will automatically be dropped before ingestion.
  - source_labels: [__name__, name, stat]
    regex: 'oracle_resource_limits;enqueue_locks;(.*)'
    target_label: __tmp_name
    replacement: 'oracle_enqueue_locks_${1}'

  # Other relabels similar to the above, in case you have other `name` and `stat` values.
  # ...

  # Drop the `name` label.
  - source_labels: [__name__]
    regex: 'oracle_resource_limits'
    target_label: name
    replacement: ''

  # Drop the `stat` label.
  - source_labels: [__name__]
    regex: 'oracle_resource_limits'
    target_label: stat
    replacement: ''

  # Set `__name__` to the value of `__tmp_name`.
  - source_labels: [__tmp_name]
    regex: '(oracle_enqueue_locks_.*)'
    target_label: __name__
    replacement: '${1}'
```
