### ISSUE TITLE
No result returned for log shipping monitor query

### ISSUE THREAD

**Issue by samuelthan** [free/sql_exporter#16]
Used the following yml file to get a specific query. 

If we copy and paste the query to the SSMS you can get a list of databases and restored delta return.

However, when using SQL exporter, services started up in services however when browsing to http://localhost:9399/metrics i recieved http 500 internal error.

I'm running MSSQL 2017, Windows Server 2016

```yml
# A collector defining standard metrics for Microsoft SQL Server.
#
# It is required that the SQL Server user has the following permissions:
#
#   GRANT VIEW ANY DEFINITION TO
#   GRANT VIEW SERVER STATE TO
#
collector_name: mssql_standard

# Similar to global.min_interval, but applies to the queries defined by this collector only.
#min_interval: 0s

metrics:
  - metric_name: mssql_monitor_secondary_logshipping
    type: gauge
    help: 'Monitor secondary sql restored delta.'
    key_labels:
      - secondary_db
    values: [restored_delta]
    query: |
      SELECT secondary_database as secondary_db, DATEDIFF(mi, last_restored_date, GETDATE()) as restored_delta FROM msdb..log_shipping_monitor_secondary
```
