### ISSUE TITLE
Load labels from JSON column

### ISSUE THREAD

**Issue by samsk** [free/sql_exporter#36]
It would be great to have a possibility to load multiple labels for a value from a JSON column returned from SQL query.

Example:
```
 - metric_name: data_check
    type: gauge
    help: 'Data processing status'
    key_labels:
      - id
    json_labels: labels
    values: [ok]
    query: |
      SELECT id, ok, labels
      FROM data_monitoring_check
```  
Database result:
```
| 888 |  0 | {"procid": "1", "procname": "download"}
| 889 |  1 | {"procid": "2", "procname": "upload"} 
```

Metrics:
```
data_check{id="888",procid="1",procname="download"} 0
data_check{id="889",procid="2",procname="upload"} 1
```
