### ISSUE TITLE
How can I add static labels to target?

### ISSUE THREAD

**Issue by farodrig** [free/sql_exporter#49]
Hi, I want to add some static labels to target. Is it posible?

ex:
```
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  data_source_name: 'sqlserver://prom_user:prom_password@dbserver1.example.com:1433'

  # Collectors (referenced by name) to execute on the target.
  collectors: [pricing_data_freshness]

  # My static labels
  labels:
    -  my_label: 'my-label-value'
    -  some-another-label: 'another-label-value'
```
