### ISSUE TITLE
non numeric labels from query

### ISSUE THREAD

**Issue by GreySpike** [free/sql_exporter#59]
I apologise if I have missed something obvious, but I'm trying to attach string values as labels and failing as all columns appear to be converted to either ints or floats.

For example, given the following collector.yml I'd like the Version to be included as a label. Version is a Semantic Version string.

```
metrics:
  - metric_name: hk_record_count
    type: counter
    help: 'Count of records identified as ready for housekeeping, and removed by housekeeping.'
    key_labels:
      - TableName
    static_labels:
      # Arbitrary key/value pair
      host: test
    value_label: 'Counters'
    values: [ExpiredCount,DeletedCount]
    value_label: 'Version'
    values: [Version]
    query_ref: hk_metrics

queries:
  # housekeeping scorecards
  - query_name: hk_metrics
    query: |
      select
        TABLE_NAME as TableName,
        VERSION as Version,
        TOTAL_EXPIRED as ExpiredCount,
        TOTAL_DELETED as DeletedCount,
        THREAD_COUNT as THREAD_COUNT
      from HOUSEKEEP_SCORECARD
      order by TABLE_NAME
```

**Comment by free** [comment]
For one, you can't have two `value_label` entries for a single metric. If that worked, it would result in a metric with inconsistent labels, something like (note the mismatched sets):
```
hk_record_count{TableName="foo",Counters="ExpiredCount"} 1
hk_record_count{TableName="foo",Counters="DeletedCount"} 2
hk_record_count{TableName="foo",Version="Version"} 3
```

So you need to define 2 separate metrics:
```
metrics:
  - metric_name: hk_record_count
    type: counter
    help: 'Count of records identified as ready for housekeeping, and removed by housekeeping.'
    key_labels:
      - TableName
    static_labels:
      host: test
    value_label: 'Counters'
    values: [ExpiredCount,DeletedCount]
    query_ref: hk_metrics

  - metric_name: hk_info
    type: counter
    help: 'Count of records identified as ready for housekeeping, and removed by housekeeping.'
    key_labels:
      - TableName
      - Version
    static_labels:
      host: test
    values: [ExpiredCount]
    query_ref: hk_metrics
```

This way you would end up with something like this instead (note that the value of the `hk_info` metric is arbitrary, you're just interested in the right `Version` label):
```
hk_record_count{TableName="foo",Counters="ExpiredCount"} 1
hk_record_count{TableName="foo",Counters="DeletedCount"} 2
hk_info{TableName="foo",Version="1.2.3"} 1
```

Else, you can simply move `Version` in your example under `key_labels`, next to `TableName` (and get rid of `values: [Version]) to end up with something like:
```
hk_record_count{TableName="foo",Version="1.2.3",Counters="ExpiredCount"} 1
hk_record_count{TableName="foo",Version="1.2.3",Counters="DeletedCount"} 2
```

As a side note, I would also use `counter` instead of `Counters`: lowercase and singular. And lowercase all other labels.
