### ISSUE TITLE
How to write values if I want to query multiple fields

### ISSUE THREAD

**Issue by tangxiaoran** [free/sql_exporter#61]
If I want to query how to write values for multiple fields, it seems that values only supports one field。
exp:
```yaml
 - metric_name: oracle_tablespace_detail
    type: gauge
    help: 'oracle_tablespace_detail.'
    values:
      - free
      - usage
      - total
    key_labels:
      - tablespace_name
      - autoextend
    query: |
......................................................
```
error:
```
[root@localhost database_exporter]#  ./database_exporter -config.file /usr/local/database_exporter/database_exporter/config/oracle_exporter.yml
I0312 10:24:03.484394   32528 main.go:53] Starting Database Exporter (version=, branch=, revision=) (go=go1.10.3, user=, date=)
I0312 10:24:03.484992   32528 config.go:18] Loading configuration from /usr/local/database_exporter/database_exporter/config/oracle_exporter.yml
F0312 10:24:03.488097   32528 main.go:57] Error creating exporter: value_label must be defined for metric with multiple values "oracle_tablespace_detail"
goroutine 1 [running]:
```

**Comment by shawbruno** [comment]
Hey how to install sql_Exporter in linux , i can't install in linux with command in readme.. do u like help me ?

**Comment by tangxiaoran** [comment]
I used this，Support Oracle 、sqlserver, platform agnostic。
https://github.com/Corundex/database_exporter



At 2020-03-12 16:29:16, "shawbruno" <notifications@github.com> wrote:

Hey how to install sql_Exporter in linux , i can't install in linux with command in readme.. do u like help me ?

**Comment by shawbruno** [comment]
i receive that of line command :

go build github.com/Corundex/database_exporter
can't load package: package github.com/Corundex/database_exporter: cannot find package "github.com/Corundex/database_exporter" in any of:
	/usr/lib/go-1.10/src/github.com/Corundex/database_exporter (from $GOROOT)
	/home/ana-aeroportos/go/src/github.com/Corundex/database_exporter (from $GOPATH)

**Comment by free** [comment]
@shawbruno, please do not hijack threads, I've tried to answer your issue directly.

@tangxiaoran, the answer to your question is in the error message: "value_label must be defined for metric with multiple values".

As is, you would get one `oracle_tablespace_detail{tablespace_name="foo",autoextend="bar"}` value (with no extra label) for each of `free`, `usage` and `total`. I.e. 3 instances of the exact same metric. You need a `type` (or something) label with the value label set to `free`/`usage`/`total` in order to differentiate between the three. E.g.

```
oracle_tablespace_detail{tablespace_name="foo",autoextend="bar",type="free"} 1
oracle_tablespace_detail{tablespace_name="foo",autoextend="bar",type="usage"} 2
oracle_tablespace_detail{tablespace_name="foo",autoextend="bar",type="total"} 3
```

But you need to tell SQL Exporter what name to use for that label, which is where the `value_label` comes in. See for example the [`mssql_io_stall_seconds`](https://github.com/free/sql_exporter/blob/master/examples/mssql_standard.collector.yml#L112) metric in `mssql_standard.collector.yml`. So you would need to rewrite your config to something like this instead (you can use something more informative instead of `"type"`):

```yaml
 - metric_name: oracle_tablespace_detail
    type: gauge
    help: 'oracle_tablespace_detail.'
    value_label: type
    values:
      - free
      - usage
      - total
    key_labels:
      - tablespace_name
      - autoextend
    query: |
        [...]
```
