### ISSUE TITLE
what metric name or collector should I use to get my instance data_source_name ? 

### ISSUE THREAD

**Issue by AmilaDevops** [free/sql_exporter#94]
I'm running sql_exporter with prometheus and I need to get the names of my data_source_name / target names (you can say as instance names as well)  as a metrics output. Because I need to use them as a drop-down for my grafana dashboard.  

Below my sql_exporter.yml file 

```
global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 3
  max_idle_connections: 3
target:
  data_source_name: 'sqlserver://prom_user:prom_password@dbserver1.example.com:1433/Hello'
  collectors: [mssql_standard]
collector_files: 
  - "*myfile.collector.yml"
```
  
  * so  in above file **sqlserver://prom_user:prom_password@dbserver1.example.com:1433/Hello**  is the one I need to get from merics output.    
 So  Is there any metric name which I don't know to add into myfile.collector.yml ?  Or how can I get that name as a metric output ? 
  
  hi @free hope you understand my question, if not please leave a message, I will provide more information. Thanks
