### ISSUE TITLE
No output data/metrics shown on /metrics

### ISSUE THREAD

**Issue by BigBadHobbit** [free/sql_exporter#96]
I have started a fresh postgres installation and a sql exporter.
After a db and table was created i have created the following config for sql exporter. When a start the service i can open UI and there are no error logs in my terminal.
The problem is that when i open localhost:9399/metrics - there is only a blank page with no metrics or some data atleast.
The query work when i use psql cli and i`ve make a test with fake daa like username or password, then sql exporter log some error but with "working" config file there is no output on /metrics.
sql exporter file
```
# Global defaults.
global:
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 0s
  # Maximum number of open connections to any one target. Metric queries will run concurrently on multiple connections,
  # as will concurrent scrapes.
  max_connections: 3
  # Maximum number of idle connections to any one target. Unless you use very long collection intervals, this should
  # always be the same as max_connections.
  max_idle_connections: 3

# The target to monitor and the collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  data_source_name: 'postgres://postgres:postgres@127.0.0.1:5432'

  # Collectors (referenced by name) to execute on the target.
  collectors: [mssql_standard]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
collector_files: 
  - "*.collector.yml"

 *.collector.yml file
```
collector_name: mssql_standard
```
# Similar to global.min_interval, but applies to the queries defined by this collector only.
#min_interval: 0s

metrics:
      # A different metric, with multiple values produced from each result row.
      - metric_name: mssql_io_stall_seconds
        type: counter
        help: 'Show delay.'
        key_labels:
          # Populated from the `db` column of the result.
          - id
        # Label populated with the value column name, configured via `values` (e.g. `operation="io_stall_read_ms"`).
        #
        # Required when multiple value columns are configured.
        value_label: operation
        # Multiple value columns: their name is recorded in the label defined by `attrubute_label` (e.g. 
        # `operation="io_stall_read_ms"`).
        values:
          - del
        query_ref: mssql_io_stall

queries:
  # Populates `mssql_io_stall` and `mssql_io_stall_total`
  - query_name: mssql_io_stall
    query: |
      select user_id as id, delay as del from test where delay > 1; 
```
